

target 'shopping001' do

  pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'
  pod 'Google-Mobile-Ads-SDK'
  pod "XCDYouTubeKit", "~> 2.5"


  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge', # Include this for RN >= 0.47
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # Needed for debugging
      'RCTAnimation', # Needed for FlatList and animations running on native UI thread
  # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'FBAudienceNetwork', '4.99.0'
  pod 'FBSDKCoreKit'

  #use_frameworks!

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
